/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aliyun_libheif_HeifNative */

#ifndef _Included_com_aliyun_libheif_HeifNative
#define _Included_com_aliyun_libheif_HeifNative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_aliyun_libheif_HeifNative
 * Method:    toRgba
 * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
 */
JNIEXPORT jboolean

extern "C" Java_com_aliyun_libheif_HeifNative_toRgba
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);


/*
 * Class:     com_aliyun_libheif_HeifNative
 * Method:    isHeic
 * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
 */
JNIEXPORT jboolean 

extern "C"  Java_com_aliyun_libheif_HeifNative_isHeic
  (JNIEnv *, jclass, jlong, jbyteArray);


/*
 * Class:     com_aliyun_libheif_HeifNative
 * Method:    multiimage_toRgba
 * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
 */
JNIEXPORT jboolean

extern "C" Java_com_aliyun_libheif_HeifNative_imagesToRgba
  (JNIEnv *, jclass, jint, jlong, jbyteArray, jobject);


/*
 * Class:     com_aliyun_libheif_HeifNative
 * Method:    GetInfo 
 * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
 */
JNIEXPORT jboolean 

extern "C" Java_com_aliyun_libheif_HeifNative_getInfo
  (JNIEnv *, jclass, jobject, jlong, jbyteArray);


#ifdef __cplusplus
}
#endif
#endif
