/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aliyun_libheif_HeifNative */

#ifndef _Included_com_aliyun_libheif_HeifNative
#define _Included_com_aliyun_libheif_HeifNative
#ifdef __cplusplus
extern "C" {
#endif
///*
// * Class:     com_aliyun_libheif_HeifNative
// * Method:    encodeBitmap
// * Signature: ([BIILjava/lang/String;)I
// */
//JNIEXPORT jint
//
//extern "C" jint Java_com_aliyun_libheif_HeifNative_encodeBitmap
//  (JNIEnv *, jclass, jbyteArray, jint, jint, jstring);
//
///*
// * Class:     com_aliyun_libheif_HeifNative
// * Method:    encodeYUV
// * Signature: ([BIILjava/lang/String;)I
// */
//JNIEXPORT jint
//extern "C" jint Java_com_aliyun_libheif_HeifNative_encodeYUV
//  (JNIEnv *, jclass, jbyteArray, jint, jint, jstring);
//
///*
// * Class:     com_aliyun_libheif_HeifNative
// * Method:    decodeHeif2RGBA
// * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)[B
// */
//JNIEXPORT jbyteArray
//
//extern "C" jbyteArray Java_com_aliyun_libheif_HeifNative_decodeHeif2RGBA
//  (JNIEnv *, jclass, jobject, jstring);
//
///*
// * Class:     com_aliyun_libheif_HeifNative
// * Method:    decodeHeif2RGBA_mem
// * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
// */
//JNIEXPORT jbyteArray
//
//extern "C" jbyteArray Java_com_aliyun_libheif_HeifNative_decodeHeif2RGBAMem
//  (JNIEnv *, jclass, jobject, jlong, jbyteArray, jstring);
//
//
///*
// * Class:     com_aliyun_libheif_HeifNative
// * Method:    isHeicImageAndGetInfo
// * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
// */
//JNIEXPORT jboolean
//
//extern "C" Java_com_aliyun_libheif_HeifNative_isHeicImageAndGetInfo
//  (JNIEnv *env,jclass type, jobject outSize, jstring srcPath_); 
//
//
///*
// * Class:     com_aliyun_libheif_HeifNative
// * Method:    isHeicImageAndGetInfoMem
// * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
// */
//JNIEXPORT jboolean 
//
//extern "C" Java_com_aliyun_libheif_HeifNative_isHeicImageAndGetInfoMem
//  (JNIEnv *, jclass, jobject, jlong, jbyteArray);


/*
 * Class:     com_aliyun_libheif_HeifNative
 * Method:    toRgba
 * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
 */
JNIEXPORT jboolean

extern "C" Java_com_aliyun_libheif_HeifNative_toRgba
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);


/*
 * Class:     com_aliyun_libheif_HeifNative
 * Method:    isHeic
 * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
 */
JNIEXPORT jboolean 

extern "C"  Java_com_aliyun_libheif_HeifNative_isHeic
  (JNIEnv *, jclass, jlong, jbyteArray);


/*
 * Class:     com_aliyun_libheif_HeifNative
 * Method:    multiimage_toRgba
 * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
 */
JNIEXPORT jboolean

extern "C" Java_com_aliyun_libheif_HeifNative_imagesToRgba
  (JNIEnv *, jclass, jint, jlong, jbyteArray, jobject);


/*
 * Class:     com_aliyun_libheif_HeifNative
 * Method:    GetInfo 
 * Signature: (Lcom/aliyun/libheif/HeifSize;Ljava/lang/String;)
 */
JNIEXPORT jboolean 

extern "C" Java_com_aliyun_libheif_HeifNative_getInfo
  (JNIEnv *, jclass, jobject, jlong, jbyteArray);


#ifdef __cplusplus
}
#endif
#endif
